# name=input("Enter your name ")
phone=input("enter the phone number")
# result=len(name)
# result=name.find("a")
# result=name.rfind("a")
# name=name.capitalize()
# name=name.upper()
# name=name.lower()
# name=name.isalpha()
# name=name.isalpha()

# phone=phone.count("-")
phone=phone.replace("-", " ")
print(help(str))
print(phone)